// <auto-generated />
using System;
using KriptoService.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KriptoService.Migrations.Migrations
{
    [DbContext(typeof(KriptoDataDb))]
    partial class KriptoDataDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("KriptoService.Domain.Models.CryptoPriceDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Change24h")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ChangePct24h")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("High24h")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Low24h")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MarketCap")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Volume24h")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FetchedAt");

                    b.HasIndex("Symbol", "Currency", "FetchedAt");

                    b.ToTable("Prices");
                });
#pragma warning restore 612, 618
        }
    }
}
