// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsService.DB;

#nullable disable

namespace NewsService.Migrations
{
    [DbContext(typeof(NewsDataDb))]
    [Migration("20260319151630_AddSourceCount")]
    partial class AddSourceCount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("NewsService.Domain.Models.NewsItemDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawDescription")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RawPublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceFeed")
                        .HasColumnType("TEXT");

                    b.Property<int>("TopicId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("NewsService.Domain.Models.NewsTopicDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSent")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .IsUnique();

                    b.HasIndex("IsSent");

                    b.HasIndex("PublishedAt");

                    b.HasIndex("SourceCount");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("NewsService.Domain.Models.NewsItemDb", b =>
                {
                    b.HasOne("NewsService.Domain.Models.NewsTopicDb", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });
#pragma warning restore 612, 618
        }
    }
}
