// <auto-generated />
using System;
using ExchangeRatesBot.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExchangeRatesBot.Migrations.Migrations
{
    [DbContext(typeof(DataDb))]
    [Migration("20260319151809_AddImportantNewsSubscribe")]
    partial class AddImportantNewsSubscribe
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ExchangeRatesBot.DB.Models.UserDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currencies")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ImportantNewsSubscribe")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastImportantNewsAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastNewsDeliveredAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NewsSubscribe")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NewsTimes")
                        .HasColumnType("TEXT");

                    b.Property<string>("NickName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Subscribe")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
